name: Publish 1.8 experimental

on:
  push:
    branches:
      - "exp/1.8"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: gradle/wrapper-validation-action@v3
      - run: cd test-mod && ./gradlew build
      - run: cd test-mod && ./gradlew genSources
        env:
          EXPERIMENTAL: true
      - run: ./gradlew build publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          EXPERIMENTAL: true